# Generated by Django 4.0.7 on 2022-10-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='/blank-profile-picture.png', upload_to='profile_images'),
        ),
    ]
