# Generated by Django 4.0.7 on 2022-10-24 10:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('391cc047-cdb9-4285-a3d8-bf6ef1af0f06'), primary_key=True, serialize=False),
        ),
    ]
